# Generated by Django 3.1.3 on 2020-11-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='your_subject',
            field=models.CharField(default='YOUR SUBJECT', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='you_email',
            field=models.EmailField(default='YOUR EMAIL', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='your_message',
            field=models.TextField(default='YOUR MESSAGE'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='your_name',
            field=models.CharField(default='YOUR NAME', max_length=30),
        ),
    ]
