# Generated by Django 3.1.3 on 2020-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famous', '0004_auto_20201114_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_to_course',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
